### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by oldtune** [yozuk/yozuk#1]
Hi, i kinda like your project. Do you have any feature on your plate to implement later? I can use my mediocre coding skill to contribute to the project.

**Comment by picoHz** [comment]
Hi! I'm really excited to have a first contributor.

I just listed some easy tasks for new contributors:
https://github.com/yozuk/yozuk/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

If you have ideas about new features, feel free to create issues.
